name: Test sm runner

on: 
  pull_request:
    branches:
      - master

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run init job"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run the code
        run: python3 app.py