name: Test sm runner

on: 
  pull_request:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run init job"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        run: echo "Run build step"